//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMBOXING.Comm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErroMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErroMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMBOXING.Comm.ErroMessage", typeof(ErroMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录失败 的本地化字符串。
        /// </summary>
        internal static string ch100 {
            get {
                return ResourceManager.GetString("ch100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以存在交易 的本地化字符串。
        /// </summary>
        internal static string ch1001 {
            get {
                return ResourceManager.GetString("ch1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额不足 的本地化字符串。
        /// </summary>
        internal static string ch1002 {
            get {
                return ResourceManager.GetString("ch1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易失败 的本地化字符串。
        /// </summary>
        internal static string ch1003 {
            get {
                return ResourceManager.GetString("ch1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在交易 的本地化字符串。
        /// </summary>
        internal static string ch1004 {
            get {
                return ResourceManager.GetString("ch1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有该Token的用户 的本地化字符串。
        /// </summary>
        internal static string ch101 {
            get {
                return ResourceManager.GetString("ch101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有改ID的用户 的本地化字符串。
        /// </summary>
        internal static string ch102 {
            get {
                return ResourceManager.GetString("ch102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败 的本地化字符串。
        /// </summary>
        internal static string ch103 {
            get {
                return ResourceManager.GetString("ch103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改积分失败 的本地化字符串。
        /// </summary>
        internal static string ch104 {
            get {
                return ResourceManager.GetString("ch104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改或增加token失败 的本地化字符串。
        /// </summary>
        internal static string ch105 {
            get {
                return ResourceManager.GetString("ch105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 题库题目为空 的本地化字符串。
        /// </summary>
        internal static string ch106 {
            get {
                return ResourceManager.GetString("ch106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有为改ID的题目 的本地化字符串。
        /// </summary>
        internal static string ch107 {
            get {
                return ResourceManager.GetString("ch107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加记录失败 的本地化字符串。
        /// </summary>
        internal static string ch108 {
            get {
                return ResourceManager.GetString("ch108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改记录失败 的本地化字符串。
        /// </summary>
        internal static string ch109 {
            get {
                return ResourceManager.GetString("ch109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string ch120 {
            get {
                return ResourceManager.GetString("ch120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string ch121 {
            get {
                return ResourceManager.GetString("ch121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string ch200 {
            get {
                return ResourceManager.GetString("ch200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统失败 的本地化字符串。
        /// </summary>
        internal static string ch500 {
            get {
                return ResourceManager.GetString("ch500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1200000 的本地化字符串。
        /// </summary>
        internal static string expirationTime {
            get {
                return ResourceManager.GetString("expirationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户进入直播间 的本地化字符串。
        /// </summary>
        internal static string InRoom {
            get {
                return ResourceManager.GetString("InRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏编号出错，请重试 的本地化字符串。
        /// </summary>
        internal static string inRoomErro {
            get {
                return ResourceManager.GetString("inRoomErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 172.16.31.250 的本地化字符串。
        /// </summary>
        internal static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录异常，已在其他地方登录 的本地化字符串。
        /// </summary>
        internal static string loginErro {
            get {
                return ResourceManager.GetString("loginErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户掉线 的本地化字符串。
        /// </summary>
        internal static string lostConn {
            get {
                return ResourceManager.GetString("lostConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XMGAME.BLL 的本地化字符串。
        /// </summary>
        internal static string mbns {
            get {
                return ResourceManager.GetString("mbns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经被请出房间 的本地化字符串。
        /// </summary>
        internal static string outRoom {
            get {
                return ResourceManager.GetString("outRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8009 的本地化字符串。
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户准备 的本地化字符串。
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 500 的本地化字符串。
        /// </summary>
        internal static string receiveTime {
            get {
                return ResourceManager.GetString("receiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string redisHost {
            get {
                return ResourceManager.GetString("redisHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6379 的本地化字符串。
        /// </summary>
        internal static string redisPort {
            get {
                return ResourceManager.GetString("redisPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D:\userLogin 的本地化字符串。
        /// </summary>
        internal static string rememberFile {
            get {
                return ResourceManager.GetString("rememberFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string roomSize {
            get {
                return ResourceManager.GetString("roomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误 的本地化字符串。
        /// </summary>
        internal static string systemErro {
            get {
                return ResourceManager.GetString("systemErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10000 的本地化字符串。
        /// </summary>
        internal static string timerTime {
            get {
                return ResourceManager.GetString("timerTime", resourceCulture);
            }
        }
    }
}
